---
- name: Ensure nebula bin directory exists
  file:
    path: "{{ nebula_bin_directory }}"
    state: directory

- name: Download release from Github (x86)
  unarchive:
    src: https://github.com/slackhq/nebula/releases/download/v{{ nebula_version }}/nebula-{{ ansible_system|lower }}-amd64.tar.gz
    dest: "{{ nebula_bin_directory }}"
    remote_src: yes
    mode: 0755
    creates: "{{ (nebula_bin_directory + '/nebula') if nebula_force_install == false else '' }}"
  when: ansible_architecture == "x86_64"

- name: Set correct user and group on the nebula binary
  ansible.builtin.file:
    path: "{{ nebula_bin_directory }}/nebula"
    owner: root
    group: root
    mode: '0755'

- name: Set correct user and group on the nebula-cert binary
  ansible.builtin.file:
    path: "{{ nebula_bin_directory }}/nebula-cert"
    owner: root
    group: root
    mode: '0755'

- name: Create configuration directory
  file:
    path: /etc/nebula
    state: directory
    mode: "0750"
